name: Packer linter

on: [push, pull_request]

jobs:
  packer:
    runs-on: ubuntu-latest
    env:
      TARGET: infosec_debian.json
    name: packer
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2
      # fix backwards incompatibilities in template
      - name: Fix Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: fix
          target: ${{ env.DAY_OF_WEEK }}
      # validate templates
      - name: Validate Template
        uses: hashicorp/packer-github-actions@master
        with:
          command: validate
          target: ${{ env.DAY_OF_WEEK }}
